/* eslint-disable quotes */

export const ApiEndPoints = {
  userlogin: `/login`,
  userlogout: `/logout`,
  refreshtoken: `/refreshtoken`,
  otpRequest: `/send/otp`,
  register: `/student/register`,
  password: `/forgot/password/change`,
  passwordvalidate: `/forgot/password/validate`,
  forgot: `/forgot/password`,
  categorySearch: `/category/search?order=asc`,
  countries: `/countries/list`,
  scoreTypes: `/scoreTypes/getAll`,
  institutions: `/institution/search?page=`,
  imageUpload: `s3/upload`,
  profile: `/student/details`,
  profileUpdate: `/student`,
  courses: `/courses/search?`,
  appliedCourses: `/application/search`,
  studentEducation: `/studentEducation`,
  courseApply: `/application/create/`,
  popularColleges: `/institution/search?page=`,
  topCourses: `/courses/search?`,
  review: `/review/create`,
};
